# Generated by Django 2.1.2 on 2018-11-21 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20181121_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='title_html',
            field=models.TextField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
